from django.conf.urls import url
from apps.beneficiario.views import *
urlpatterns = [
    #url(r'^beneficiario_create/(?P<tipo>[cabeza|beneficiario]+)$', beneficiario_create, name='beneficiario_create'),
    url(r'^beneficiario_create$', beneficiario_create, name='beneficiario_create'),
    url(r'^beneficiario_consulta$', beneficiario_consulta, name='beneficiario_consulta'),
    url(r'^datosBasicos$', datosBasicos, name='datosBasicos'),
    url(r'^datosBasicosEditar/(?P<id_ben>\d+)/$', datosBasicosEditar, name='datosBasicosEditar'),
    url(r'^datosCaracterizacion/(?P<id_ben>\d+)/$', datosCaracterizacion, name='datosCaracterizacion'),
    url(r'^datosCaracterizacionEditar/(?P<id_ben>\d+)/$', datosCaracterizacionEditar, name='datosCaracterizacionEditar'),
    url(r'^datosProcedencia/(?P<id_ben>\d+)/$', datosProcedencia, name='datosProcedencia'),
    url(r'^datosProcedenciaEditar/(?P<id_ben>\d+)/$', datosProcedenciaEditar, name='datosProcedenciaEditar'),
    url(r'^datosEducacion/(?P<id_ben>\d+)/$', datosEducacion, name='datosEducacion'),
    url(r'^datosEducacionEditar/(?P<id_ben>\d+)/$', datosEducacionEditar, name='datosEducacionEditar'),
    url(r'^datosLaborales/(?P<id_ben>\d+)/$', datosLaborales, name='datosLaborales'),
    url(r'^datosLaboralesEditar/(?P<id_ben>\d+)/$', datosLaboralesEditar, name='datosLaboralesEditar'),
    url(r'^datosResidencia/(?P<id_ben>\d+)/$', datosResidencia, name='datosResidencia'),
    url(r'^datosResidenciaEditar/(?P<id_ben>\d+)/$', datosResidenciaEditar, name='datosResidenciaEditar'),
    url(r'^datosResidenciaMaterial/(?P<id_ben>\d+)/$', datosResidenciaMaterial, name='datosResidenciaMaterial'),
    url(r'^datosResidenciaMaterialEditar/(?P<id_ben>\d+)/$', datosResidenciaMaterialEditar, name='datosResidenciaMaterialEditar'),
    url(r'^datosResidenciaMaterialdos/(?P<id_ben>\d+)/$', datosResidenciaMaterialdos, name='datosResidenciaMaterialdos'),
    url(r'^datosResidenciaMatdosEdit/(?P<id_ben>\d+)/$', datosResidenciaMatdosEdit, name='datosResidenciaMatdosEdit'),
    url(r'^datosCocina/(?P<id_ben>\d+)/$', datosCocina, name='datosCocina'),
    url(r'^datosCocinaEditar/(?P<id_ben>\d+)/$', datosCocinaEditar, name='datosCocinaEditar'),
    url(r'^documentos/(?P<id_ben>\d+)/$', documentos, name='documentos'),
    url(r'^verdocumentos$', verdocumentos, name='verdocumentos'),
    url(r'^generaCarnet$', generaCarnet, name='generaCarnet'),
    url(r'^activaCarnet/(?P<id_ben>\d+)/$', activaCarnet, name='activaCarnet'),
    url(r'^ciudadesAjax$', ciudadesAjax, name='ciudadesAjax'),
    url(r'^beneficiarioAjax$', beneficiarioAjax, name='beneficiarioAjax'),
    url(r'^imprimirCarnet$', imprimirCarnet, name='imprimirCarnet'),
    url(r'^profesion_nueva$', profesion_nueva, name='profesion_nueva'),
    url(r'^eps_nueva$', eps_nueva, name='eps_nueva'),
    url(r'^educativa_nueva$', educativa_nueva, name='educativa_nueva'),

]
