# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0002_beneficiario_tipovivienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipovivienda',
            name='tipoVivienda',
            field=models.CharField(max_length=60),
        ),
    ]
