# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0003_auto_20161110_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='grupoHogar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabezaHogar', models.CharField(max_length=1)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario')),
            ],
        ),
    ]
