# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0004_grupohogar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jefehogar',
            name='jefe',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='hechoVictimizante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.HechoVictimizante'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JefeHogar',
        ),
    ]
