# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0005_auto_20161113_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcupaVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupaVivienda', models.CharField(max_length=60)),
            ],
        ),
    ]
