# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0006_ocupavivienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario_grupoHogar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario')),
            ],
        ),
        migrations.RemoveField(
            model_name='grupohogar',
            name='beneficiario',
        ),
        migrations.RemoveField(
            model_name='grupohogar',
            name='cabezaHogar',
        ),
        migrations.AddField(
            model_name='grupohogar',
            name='codigo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario_grupohogar',
            name='grupoHogar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.GrupoHogar'),
        ),
    ]
