# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0007_auto_20161117_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='eps',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Eps'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='estadoCivil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.EstadoCivil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='institucionEducativa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.InstitucionEducativa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='nivelEducativo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.NivelEducativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='ocupaVivienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.OcupaVivienda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiario_grupohogar',
            name='grupoHogar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.GrupoHogar'),
        ),
    ]
