# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0008_auto_20161117_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='beneficiario_grupohogar',
            name='grupoHogar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.GrupoHogar'),
        ),
        migrations.AlterField(
            model_name='etnia',
            name='etnia',
            field=models.CharField(max_length=60),
        ),
    ]
