# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0009_auto_20161119_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='ciudadProcedencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Ciudad_procedencia', to='beneficiario.Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='fechaResidencia',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ciudad_residencia', to='beneficiario.Ciudad'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='genero',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1),
        ),
        migrations.AlterField(
            model_name='beneficiario_grupohogar',
            name='grupoHogar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.GrupoHogar'),
        ),
    ]
