# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0010_auto_20161120_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='regimen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Regimen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiario_grupohogar',
            name='grupoHogar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.GrupoHogar'),
        ),
    ]
