# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0014_auto_20161120_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='familiasAccion',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='beneficiario_grupohogar',
            name='grupoHogar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.GrupoHogar'),
        ),
    ]
