# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0016_auto_20161121_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiario',
            old_name='ciudad',
            new_name='ciudadResidencia',
        ),
        migrations.AlterField(
            model_name='beneficiario_grupohogar',
            name='grupoHogar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.GrupoHogar'),
        ),
    ]
