# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0019_auto_20161205_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario_grupohogar',
            name='beneficiario',
        ),
        migrations.RemoveField(
            model_name='beneficiario_grupohogar',
            name='grupoHogar',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='cabeza_hogar_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Beneficiario_grupoHogar',
        ),
        migrations.DeleteModel(
            name='grupoHogar',
        ),
    ]
