# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0022_beneficiario_cabeza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='cabeza_hogar_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario'),
        ),
    ]
