# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0025_auto_20170114_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='codigoUV',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='telefonoCelular',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='telefonoFijo',
            field=models.IntegerField(null=True),
        ),
    ]
