# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0033_auto_20170119_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='ciudadDeclara',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Ciudad_declara', to='beneficiario.Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='fechaDeclara',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='revictimizado',
            field=models.BooleanField(default=False),
        ),
    ]
