# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0035_auto_20170120_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='estudiaActualmente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='kitEscolar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='otrosEstudios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='otrosEstudiosD',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='uniforme',
            field=models.BooleanField(default=False),
        ),
    ]
