# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0037_auto_20170219_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='ingresos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Ingresos'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='ocupacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Ocupacion'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='profesion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Profesion'),
        ),
    ]
