# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0040_beneficiario_extranjero'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='pagaOtro',
            field=models.NullBooleanField(),
        ),
    ]
