# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0041_beneficiario_pagaotro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='documentoCabeza',
            field=models.IntegerField(null=True),
        ),
    ]
