# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0042_auto_20170225_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='HechoBeneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='hechoVictimizante',
        ),
        migrations.AddField(
            model_name='hechobeneficiario',
            name='beneficiario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario'),
        ),
        migrations.AddField(
            model_name='hechobeneficiario',
            name='hecho_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.HechoVictimizante'),
        ),
    ]
