# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0043_auto_20170225_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hechobeneficiario',
            old_name='beneficiario_id',
            new_name='beneficiario',
        ),
        migrations.RenameField(
            model_name='hechobeneficiario',
            old_name='hecho_id',
            new_name='hecho',
        ),
    ]
