# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0044_auto_20170225_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='tservicio',
            field=models.NullBooleanField(),
        ),
    ]
