# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0045_beneficiario_tservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='detDiscacidad',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
