# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0047_beneficiario_embarazo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hogar',
            old_name='Inodoro',
            new_name='inodoro',
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='ingresos',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
