# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0048_auto_20170228_0027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingresos',
        ),
    ]
