# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0049_delete_ingresos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEstablecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('tipo', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='tipoEstablecimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.TipoEstablecimiento'),
            preserve_default=False,
        ),
    ]
