# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0050_auto_20170228_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='ultimoAno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
