# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-03 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0051_beneficiario_ultimoano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='ultimoAno',
            field=models.CharField(max_length=1),
        ),
    ]
