# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-04 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0057_auto_20170304_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadmes',
            name='codigo',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
