# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0063_beneficiario_percibe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hechobeneficiario',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hecho', to='beneficiario.Beneficiario'),
        ),
        migrations.AlterField(
            model_name='hechobeneficiario',
            name='hecho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiario', to='beneficiario.HechoVictimizante'),
        ),
    ]
