# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0064_auto_20170314_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hechobeneficiario',
            name='beneficiario',
        ),
        migrations.RemoveField(
            model_name='hechobeneficiario',
            name='hecho',
        ),
        migrations.DeleteModel(
            name='HechoBeneficiario',
        ),
    ]
