# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0067_auto_20170315_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='hechovictimizante',
            name='beneficiarios',
            field=models.ManyToManyField(related_name='hechos', to='beneficiario.Beneficiario'),
        ),
    ]
