# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0069_remove_hechovictimizante_beneficiarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='HechoBeneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario')),
                ('hecho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.HechoVictimizante')),
            ],
        ),
    ]
