# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0073_auto_20170316_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='detDiscacidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.DiscapacidadDetalle'),
            preserve_default=False,
        ),
    ]
