# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0074_auto_20170316_0333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiario',
            old_name='detDiscacidad',
            new_name='detDiscapacidad',
        ),
    ]
