# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0075_auto_20170316_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='detDiscapacidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.DiscapacidadDetalle'),
        ),
    ]
