# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0076_auto_20170316_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='restitucionPredio',
            field=models.NullBooleanField(),
        ),
    ]
