# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0078_auto_20170322_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogar',
            name='estratoPredio',
            field=models.IntegerField(choices=[('1', 'BAJO-BAJO'), ('2', 'BAJO'), ('3', 'MEDIO-BAJO'), ('4', 'MEDIO'), ('5', 'MEDIO-ALTO'), ('6', 'ALTO')], null=True),
        ),
    ]
