# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0079_auto_20170322_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogar',
            name='cuartos',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hogar',
            name='cuartosDuerme',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hogar',
            name='cuartosOcupa',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hogar',
            name='grupos',
            field=models.SmallIntegerField(null=True),
        ),
    ]
