# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0081_auto_20170322_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='hogar',
            name='cabezaHogar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario'),
        ),
    ]
