# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0082_hogar_cabezahogar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('metodo', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPared',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('material', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('material', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='hogar',
            name='basura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Basura'),
        ),
        migrations.AlterField(
            model_name='hogar',
            name='materialPiso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.MaterialPiso'),
        ),
        migrations.AlterField(
            model_name='hogar',
            name='materialVivienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.MaterialPared'),
        ),
        migrations.RemoveField(
            model_name='hogar',
            name='servicioPublico',
        ),
        migrations.AddField(
            model_name='hogar',
            name='servicioPublico',
            field=models.ManyToManyField(to='beneficiario.ServicioPublico'),
        ),
    ]
