# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0083_auto_20170322_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inodoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('servicio', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='hogar',
            name='inodoro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Inodoro'),
        ),
    ]
