# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0084_auto_20170323_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogar',
            name='inodoro',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Inodoro',
        ),
    ]
