# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0085_auto_20170323_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hogar',
            name='cabezaHogar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario'),
            preserve_default=False,
        ),
    ]
