# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0087_remove_hogar_cabezahogar'),
    ]

    operations = [
        migrations.AddField(
            model_name='hogar',
            name='cabezaHogar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario'),
            preserve_default=False,
        ),
    ]
