# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0088_hogar_cabezahogar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hogar',
            name='materialPiso',
        ),
    ]
