# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0090_hogar_materialpiso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='fechaResidencia',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='ocupaVivienda',
        ),
        migrations.AddField(
            model_name='hogar',
            name='fechaResidencia',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hogar',
            name='ocupaVivienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beneficiario.OcupaVivienda'),
            preserve_default=False,
        ),
    ]
