# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0091_auto_20170323_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='hogar',
            name='continuoAgua',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='hogar',
            name='llegaAgua',
            field=models.NullBooleanField(),
        ),
    ]
