# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0094_auto_20170406_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('fechaExpide', models.DateField(null=True)),
                ('fechaVence', models.DateField(null=True)),
                ('estado', models.NullBooleanField()),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiario.Beneficiario')),
            ],
        ),
    ]
