# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-26 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0096_auto_20170525_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='hogar',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
