# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-28 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiario', '0097_hogar_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnet',
            name='grupo',
            field=models.IntegerField(default=1070593028),
            preserve_default=False,
        ),
    ]
